name: Renovate

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

env:
  RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
  GITHUB_COM_TOKEN: ${{ secrets.GITHUB_COM_TOKEN }}
  RENOVATE_REPOSITORIES: ${{ secrets.RENOVATE_REPOSITORIES }}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v38.1.0
        with:
          token: ${{ env.RENOVATE_TOKEN }}
